### PR TITLE
Add Gateway to the Great Books collection

### PR DESCRIPTION
**Pull request by bentley**

### CODE REVIEW

**Comment by acabal** [comment]
Thanks!

All these collections are becoming tough to track, especially as we fill out the corpus.

Would you be interested in creating a master spreadsheet to track all of these big collections, so that we can search all in one place?

For work we don't have yet, publication year would be good to know so that we can have an idea when they might enter the public domain.

**Comment by bentley** [comment]
I agree with the idea. I think a single repository containing one spreadsheet per collection would be the best option, for the following reasons:

- it’s beneficial to keep the spreadsheet data in the same order as the collections themselves
- some collections will need to keep track of different kinds of data (e.g., *Gateway* distinguishes between short stories, essays, and selections, irrelevant to *Great Books* which only contains long-form works)
- a single repository is about as easily searchable as a single spreadsheet
- smaller spreadsheets are more manageable in general

I might take a stab at creating spreadsheets for others mentioned in the corpus but I won’t commit to that. At the moment the only sets I’m really interested in are *Great Books*, *Gateway*, and *Harvard Classics* (which I haven’t compiled yet).

My existing spreadsheets do keep track of PD date of copyrighted works. After the experience of maintaining the *Great Books* spreadsheet for several months, I settled on the following columns when initializing the *Gateway* spreadsheet:

- Author
- Work
- PD status/year
- Suitable for SE?
- SE name (if produced)

(Aside: I do strongly favor using Git for this. If the spreadsheets are kept in Google Sheets, I personally will not edit them.)

**Comment by acabal** [comment]
I think one spreadsheet file that holds all of the collections as subsheets would be best, because then we can easily search through the whole thing when looking for books or missing entries, instead of having to search through many different files. Unless we're talking about CSV, we can't grep through multiple spreadsheets en masse easily.

Re. Harvard Classics, I've considered that one in the past but it's not a good fit for SE because it contains a lot of science work and short work that would otherwise have to go in a collection. It wouldn't make a lot of sense to put the "Harvard Classics" label on a big collection just because one very short item within it is included.

If you want to start that spreadsheet, go ahead and commit it to the web repo for now. We can link to it from a page on the site somewhere.

**Comment by bentley** [comment]
I was indeed referring to the ability to `git grep` (or GitHub search) across multiple CSVs.

**Pull request merged**
